---
- name: Install CAs on OSG
  package:
    name: "{{ grid_ca_polices_pkgs.osg }}"
    state: latest
  when: grid_middleware == "OSG"

- name: Install CAs on UMD
  block:
    - name: Install CA policy packages for UMD
      package:
        name: "{{ grid_ca_polices_pkgs.umd }}"
        state: latest
    - yum:
        name: "https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm"
        state: present
    - yum:
        name: "wlcg-voms-{{ item }}"
      with_items: grid_vos
      ignore_errors: true
    - yum:
        name: "wlcg-iam-vomses-{{ item }}"
      with_items: grid_vos
      ignore_errors: true
    - yum:
        name: "wlcg-iam-lsc-{{ item }}"
      with_items: grid_vos
      ignore_errors: true
  when: grid_middleware == "UMD"
