---
- name: Generate CA CERT and KEY
  block:
    - shell: "openssl ecparam -genkey -name prime256v1 -out {{ ca_info.caname }}.key"
    - shell: "openssl req -new -nodes -sha384 -key {{ ca_info.caname }}.key -subj \"{{ ca_info.cn }}\" -out {{ ca_info.caname }}.csr"
    - shell: "openssl req -new -x509 -sha384 -set_serial 1 -days 30 -key {{ ca_info.caname }}.key -subj \"{{ ca_info.cn }}\" -out {{ ca_info.caname }}.crt"
    - name: Copy CA certificate
      copy:
        src: "{{ grid_dummy_ca.crt }}"
        dest: "/etc/grid-security/certificates/{{ ca_info.caname }}.pem"
    - name: Calculate hash
      shell: openssl x509 -noout -in CA.crt -hash
      register: ca_hash

    - name: Create link
      file:
        src:  "/etc/grid-security/certificates/{{ ca_info.caname }}.pem"
        dest: "/etc/grid-security/certificates/{{ ca_hash.stdout }}.0"
        state: link
    - name: Copy signing_policy 
      template:
        src: templates/dummy.signing_policy.j2
        dest: "/etc/grid-security/certificates/{{ ca_info.caname }}.signing_policy"
    - name: Create link for signing_polocy
      file:
        src:  "/etc/grid-security/certificates/{{ ca_info.caname }}.signing_policy"
        dest: "/etc/grid-security/certificates/{{ ca_hash.stdout }}.signing_policy"
        state: link
  when: generate_grid_dummy_ca
- name: Generate dummy hostcertificate
  block:
    - name: Calculate hash
      shell: "openssl x509 -noout -in /etc/grid-security/certificates/{{ ca_info.caname }}.pem -hash"
      register: ca_hash

    - name: Create private dir
      file:
        path: /etc/grid-security/private
        state: directory
        mode: 0600

    - name: Copy CA key
      copy:
        src: "{{ grid_dummy_ca.key }}"
        dest: /etc/grid-security/private/{{ ca_info.caname }}.key
        mode: 0600

    - name: Generate private key
      command: openssl genrsa -out /etc/grid-security/hostkey.pem 2048
      args:
        creates: /etc/grid-security/hostkey.pem

    - name: Set the mode of the private key
      file:
        path: /etc/grid-security/hostkey.pem
        mode: 0400

    - name: Generate certificate request
      command: >
        openssl req -new -sha256
        -key /etc/grid-security/hostkey.pem
        -subj "{{ ca_info.target }}{{ ansible_fqdn }}"
        -out /etc/grid-security/hostcert.csr
      args:
        creates: /etc/grid-security/hostcert.csr

    - name: Sign the certificate request
      command: >
        openssl x509 -req -in /etc/grid-security/hostcert.csr
        -CA /etc/grid-security/certificates/{{ ca_info.caname }}.pem
        -CAkey /etc/grid-security/private/{{ ca_info.caname }}.key
        -out /etc/grid-security/hostcert.pem -sha256
        -set_serial {{ 1000000 | random(seed=inventory_hostname) }}
      args:
        creates: /etc/grid-security/hostcert.pem
   
  when: generate_grid_dummy_host_certificate 
