---
- name: Install fetch-crl
  package:
    name: fetch-crl
    state: present

- name: Configure fetch-crl
  template:
    src: fetch-crl.conf.j2
    dest: /etc/fetch-crl.conf

- name: Initial run of fetch-crl
  command: /usr/sbin/fetch-crl
  changed_when: false
  ignore_errors: true
  when: run_fetchcrl

- name: Start timer for fetch-crl
  systemd_service:
    name: fetch-crl.timer
    state: started
    enabled: true
