---
- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: present

- name: Install OSG repository
  yum: 
    name: "https://repo.opensciencegrid.org/osg/3.6/osg-3.6-el{{ 7 }}-release-latest.rpm"
    state: latest
    disable_gpg_check: yes

