---
- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: present
  when: ansible_distribution_major_version == "7" 

- name: Install repository
  include_tasks: "{{ grid_middleware | lower }}.yml"
