---
- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: present
  when: ansible_distribution_major_version == "7" 

- name: Install OSG repository
  yum: 
    name: "https://repo.opensciencegrid.org/osg/{{ grid_osg_version }}/osg-{{ grid_osg_version }}-el{{ ansible_distribution_major_version }}-release-latest.rpm"
    state: latest
    disable_gpg_check: yes

