---
- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: present
  when: ansible_distribution_major_version == "7" 

- name: Install OSG repository
  yum: 
    name: "https://repo.opensciencegrid.org/osg/{{ grid_osg_version }}/osg-{{ grid_osg_version }}-el{{ ansible_distribution_major_version }}-release-latest.rpm"
    state: latest
    disable_gpg_check: yes
  when:  grid_middleware == "OSG"
- name: Install UMD repository
  yum: 
    name: "http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm"
    state: latest
    disable_gpg_check: yes
  when: (grid_middleware == "UMD") and (ansible_distribution_major_version == "7")

