---
- name: Install UMD repository
  yum: 
    name: "http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm"
    state: latest
    disable_gpg_check: yes
  when: ansible_distribution_major_version == "7"
- name: Failed if middleware is not installed
  fail: 
    msg: UMD middleware support EL7 only.
  when: ansible_distribution_major_version != "7"
