---
- name: Install UMD repository
  yum: 
    name: "http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm"
    state: latest
    disable_gpg_check: yes
  when: ansible_distribution_major_version == "7"
- name: Install EGI TrustAnchors for CA
  copy:
    dest: /etc/yum.repos.d/EGI-trustanchors.repo
    content: |
      [EGI-trustanchors]
      name=EGI-trustanchors
      baseurl=https://repository.egi.eu/sw/production/cas/1/current/
      gpgkey=https://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3
      gpgcheck=1
      enabled=1

