---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Enable EPEL repository
      package:
        name: epel-release
        state: present

  roles:
    - role: geonmo.grid
      vars:
        grid_dummy_host_certificate: true
